### ISSUE TITLE
bugfix for graphql MoneyField

### ISSUE THREAD

**Issue by briancappello** [UpliftAgency/django-money#3]
@pcraciunoiu I don't have push permissions for this repo; this bugfix is required for hotspring (not really sure how we didn't hit this before, but yea...)

```diff
index da93ff9..8ee56cb 100644
@@ -23,6 +23,9 @@ class MoneyField(Scalar):
 
     @staticmethod
     def parse_value(value):
+        if isinstance(value, Money):
+            return value
+
         amount, currency = value.split(" ")
         return Money(amount=float(amount), currency=currency)
 ```

**Comment by pcraciunoiu** [comment]
@briancappello looks good, you should have permissions now so you can push this and update PR 207.

**Comment by briancappello** [comment]
Fixed by https://github.com/UpliftAgency/django-money/pull/4
